### ISSUE TITLE
Finalize strategy meta

### ISSUE THREAD

**Issue by milkyklim** [yearn/yearn-meta#14]
TODO: 
- [x] remove duplicate strats or combine strats with generalized description 
- [x] fix file paths
- [x] rename all starts to have generic names
- [x] add protocols touched by strategies

**Comment by DarkGhost7** [comment]
Has this been finished or anything I can help with?
